INSERT INTO Medicamentos (nome, indicacao, manha, tarde, noite)
VALUES  ('remedio_doenca1', '1 x ao dia', true,false,false),
        ('remedio_doenca2', '1 x ao dia', false,true,false),
		('remedio_doenca3', '1 x ao dia', true,false,false),
		('remedio_doenca4', '1 x ao dia', false,false,true),
		('remedio_doenca5', '1 x ao dia', false,true,false),
		('remedio_doenca6', '2 x ao dia', false,true,true),	
		('remedio_doenca7', '2 x ao dia', true,true,false),
		('remedio_doenca8', '2 x ao dia', false,true,true),
		('remedio_doenca9', '2 x ao dia', true,true,false),
		('remedio_doenca10', '2 x ao dia', true,false,true),
		('remedio_doenca11', '2 x ao dia', false,true,true),
		('remedio_doenca12', '2 x ao dia', true,false,true),
		('remedio_doenca13', '3 x ao dia', true,true,true),
		('remedio_doenca14', '3 x ao dia', true,true,true),
		('remedio_doenca15', '3 x ao dia', true,true,true),
		('remedio_doenca16', '3 x ao dia', true,true,true),
		('remedio_doenca17', '3 x ao dia', true,true,true),
		('remedio_doenca18', '3 x ao dia', true,true,true),
		('remedio_doenca19', '3 x ao dia', true,true,true),
		('remedio_doenca20', '3 x ao dia', true,true,true),
		('remedio_doenca21', '3 x ao dia', true,true,true)